name: manually trigger teh workflow
on: 
  workflow_dispatch
    inputs:
      string:
        description: A string input
        type: string
        required: true
        default: "Default value"

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF