name: Docker
on: workflow_dispatch

jobs: 
  docker-job:
    runs-on: fedora-latest
    container:
      image: ibmcom/websphere-traditional
    steps:
      - name: Log node and OS versions
        run: |
          ls -l /opt/IBM/WebSphere/AppServer/

