name: Docker
on: workflow_dispatch

jobs: 
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: ibmcom/websphere-traditional
    steps:
      - name: Log node and OS versions
        run: |
          cat /etc/os-release

